# define configuration space
x_range: [0,500]  # x coordinate
y_range: [-500,500]  # y coordinate

# define vehicle parameters
min_turn_radius: 5.0  # m

# waypoints: [[50,50], [50,0], [0,50]]
waypoints: [[47,46],[48,47]]
#waypoints: [[42,41],[43,42]]
# waypoints: [[55,50],[55,40],[30,20]]